void seed_o(client *c) {...@\Suppressnumber@ @\Reactivatenumber{4}@
  for (j = 4; j < c->argc; j++) { ...
    if (!strcasecmp(c->argv[j]->ptr, "idle@\Suppressnumber@
     time") && (c->argc + ~j) >= 1 && lfu_freq==-1)@\Reactivatenumber{6}@  
    ...
  } ...
}